/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "compress.h"


void
compressimage_1(char *host, char *x)
{
	CLIENT *clnt;
	int  *result_1;
	images  image_compression_function_1_arg;

#ifndef	DEBUG
	image_compression_function_1_arg.a = x;
	clnt = clnt_create (host, COMPRESSIMAGE, COMPRESS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = image_compression_function_1(&image_compression_function_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("Result from compression function:  %s", result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *image_name;
	image_name = malloc(100);

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	strcpy(image_name, argv[2]);
	
	compressimage_1 (host, image_name);
exit (0);
}
